name: cathai_attendance
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  
  flutter_swiper_null_safety: ^1.0.2
  circle_progress_bar: ^0.1.2
  percent_indicator: ^4.2.2
  expandable: ^5.0.1
  get: ^4.6.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/sunny.png
    - assets/images/clear.jpg

