// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNH3Wsmt50QZZ09Goa8qosoa3AUFerQk',
    appId: '1:738803069313:web:fbc180ffd0a6ea9ad7b880',
    messagingSenderId: '738803069313',
    projectId: 'connectingfirebasedbtopy-a2562',
    authDomain: 'connectingfirebasedbtopy-a2562.firebaseapp.com',
    databaseURL: 'https://connectingfirebasedbtopy-a2562-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'connectingfirebasedbtopy-a2562.appspot.com',
    measurementId: 'G-74DZQV73MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCswOgLNNmMiUwHuZKAiGT0YouYsz7Y97g',
    appId: '1:738803069313:android:0fe7119b991b7887d7b880',
    messagingSenderId: '738803069313',
    projectId: 'connectingfirebasedbtopy-a2562',
    databaseURL: 'https://connectingfirebasedbtopy-a2562-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'connectingfirebasedbtopy-a2562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-MCyEhUq4aoCdT78fZyaQaf4pBgnwVRw',
    appId: '1:738803069313:ios:33a680a0a18d637cd7b880',
    messagingSenderId: '738803069313',
    projectId: 'connectingfirebasedbtopy-a2562',
    databaseURL: 'https://connectingfirebasedbtopy-a2562-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'connectingfirebasedbtopy-a2562.appspot.com',
    iosClientId: '738803069313-r6gt1g5kv4hu4mprva4v029nhbckpgcj.apps.googleusercontent.com',
    iosBundleId: 'com.cathai.cuhk.cathaiAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-MCyEhUq4aoCdT78fZyaQaf4pBgnwVRw',
    appId: '1:738803069313:ios:33a680a0a18d637cd7b880',
    messagingSenderId: '738803069313',
    projectId: 'connectingfirebasedbtopy-a2562',
    databaseURL: 'https://connectingfirebasedbtopy-a2562-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'connectingfirebasedbtopy-a2562.appspot.com',
    iosClientId: '738803069313-r6gt1g5kv4hu4mprva4v029nhbckpgcj.apps.googleusercontent.com',
    iosBundleId: 'com.cathai.cuhk.cathaiAttendance',
  );
}
